### ISSUE TITLE
How can I run generate in both GPUs? I tried to wrap main LM into DAtaparallel but still using only one.

### ISSUE THREAD

**Issue by Nozima29** [microsoft/analysing_pii_leakage#10]

**Comment by LuckMonkeys** [comment]
@Nozima29 Could you please share more details about your solution with multiple GPUs?

**Comment by Nozima29** [comment]
@LuckMonkeys not sure if it's actually correct way, but I simply loaded the model with `load_in_8bit=True` and `device_map='auto' `in language_model.py the model started to run in both GPUs.

**Comment by LuckMonkeys** [comment]
> @LuckMonkeys not sure if it's actually correct way, but I simply loaded the model with `load_in_8bit=True` and `device_map='auto' `in language_model.py the model started to run in both GPUs.

Thanks for your response! I'm not very familiar with the API for transformers, but your suggestion worked！
