### ISSUE TITLE
Potential issues in real_dataset.py

### ISSUE THREAD

**Issue by Rachelxuan11** [microsoft/analysing_pii_leakage#14]
Hi dear authors, thanks for sharing the wonderful code! 

I notice two potential issues in real_dataset.py:
1. the function `def shuffle` in real_dataset.py  does not shuffle data. Should it be "self._base_dataset = self._base_dataset.shuffle()"?
3. Is the "_tokenized_base_dataset" in real_dataset.py redundant? Only self._base_dataset is used in the iteration. This may result in a not-working `def select` in real_dataset.py.

Could you please check these potential issues and make it correct? Thanks!

**Comment by s-zanella** [comment]
You are right on both points, thanks for noticing this and opening an issue.

We only use `shuffle()` and `select()` to 

1. Choose a subset of the eval split of datasets to speed up the computation of metrics reported during training (https://github.com/microsoft/analysing_pii_leakage/blob/04ce67b4adf5141f99beab7471688d6d6e18a77a/src/pii_leakage/models/language_model.py#L319)
2. Randomizing the order in which we process training sequences when evaluating reconstruction attacks (https://github.com/microsoft/analysing_pii_leakage/blob/04ce67b4adf5141f99beab7471688d6d6e18a77a/examples/evaluate.py#L89)

Fortunately, neither of these uses should affect the results we reported.
