### ISSUE TITLE
Where can I download data and how to use my own data?

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [microsoft/analysing_pii_leakage#2]
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/31b6fa38-2f8d-46d9-a0ed-27556cca826a)
I use the code fine_tune.py and it start to download from huggingface. But by this way I can't see the data structure like what is in the "train" folder and what's in the "test" folder. So I want to download them by myself. So where can I download the data and how to use my own data?

**Comment by nilslukas** [comment]
You can provide a different dataset by changing the dataset_path field of the dataset_args in the configuration file (in the configs folder).

**Comment by Ethan-Chen-plus** [comment]
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/9202ba7e-56aa-46ba-a129-ae92e0dd4002)
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/b984e904-cd88-4fbe-ab73-fbd3bcf18f36)
The dataset configs just have one difference: scrubbed undefended in dataset_mode.And the dataset_path is exactly a dir.
dataset_path: ../src/pii_leakage/extern/echr
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/8ed849cc-a506-4845-8c58-dd614e811fac)

I can use URL to change my data
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/877f321e-56ae-4c33-a521-aa27ca85f9b3)

and I see data will be preprocess:
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/229a8084-93c1-4812-86bd-bed9848c4b36)
but I don't know how 'CustomECHRBuilder' works. 
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/425e0b1b-01df-4362-952b-0faea617fcfc)

**Comment by nilslukas** [comment]
Let's say you want to add a dataset such as Enron. You would have to create a folder at src/pii_leakage/extern/enron, create a file enron.py and define the location of your dataset, the training-testing split, and so forth. You can likely copy most of the echr.py file's content.

**Comment by Ethan-Chen-plus** [comment]
@nilslukas  Thanks a lot. And could you tell me why this happened:
I define the location of my dataset: "url": "/code/analysing_pii_leakage_ms/data/ecthr_cases"
and load the yaml
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/eafbf5e8-d062-447a-9792-d9502704ae4c)
However it still download and preparing data. How to solve this?

**Comment by Ethan-Chen-plus** [comment]
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/534a35dc-de5e-407f-aee8-aa7f32f68ec9)

After I use data_dir in load_dataset, it still downloads something from internet.

**Comment by Ethan-Chen-plus** [comment]
@nilslukas 
The problem above has been solved.
But I have another problem:
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/26ce1b59-756f-4fdc-a965-03de443a08de)

the sample speed is too slow:262580 and 7000 for 30 minutes.
It may cost me 18 hours to finish load data.

**Comment by s-zanella** [comment]
### Inspecting downloaded datasets

HuggingFace datasets caches downloaded datasets, so if you want to inspect any dataset after it's downloaded you can find the splits stored in Apache Arrow format in your HF datasets cache folder (the default is `~/.cache/huggingface/datasets`). The same holds for the NER-tagged and scrubbed datasets that our code generates--they are generated once and cached.

### Slow generation of splits

This process is slow because every piece of text is processed using Flair, even for undefended datasets (we need the tagged text for evaluation anyway). You need to do this only once, every subsequent run will load the cached splits.
