### ISSUE TITLE
Errors in generate data

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [microsoft/analysing_pii_leakage#4]
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/d5e628a6-6016-49e9-83d7-347d8b8b3427)
Could you tell me why this happened?

**Comment by colored-dye** [comment]
You cannot do something like this in Python:

```python
s = "123456"
s[3] = "4"
print(s)
```

Replace the 77th line of code in `src/pii_leakage/ner/flair_tagger.py` with:

```python
            # text[pii.start:pii.end] = self.ner_args.anon_token
            text_prefix = text[:pii.start]
            text_suffix = text[pii.end:]
            text = text_prefix + self.ner_args.anon_token + text_suffix
```
